stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mkdir build/
    - cd build
    - cmake ..
    - make -j

test:
  stage: test
  script:
    - mkdir build/
    - cd build
    - cmake ..
    - make -j
    - ctest -V