stages:
  - build
  - test
  - deploy

# Until sharing artifacts between jobs won't be implemented this stage
# is disabled.
#build:
#  stage: build
#  script:
#    - mkdir build/
#    - cd build
#    - cmake ..
#    - make -j 4

test:
  stage: test
  script:
    - git submodule init
    - git submodule update
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4
    - ctest -V