image: wraithbb/lynxware-cpp

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4
#  artifacts:
#      paths:
#          - build/
    
test:
    stage: test
    script:
        - ls -la
        - cd build/
        - ctest -V
    dependencies:
        - build
        