image: wraithbb/lynxware-cpp

stages:
  - build
  - test
  - deploy

# Until sharing artifacts between jobs won't be implemented this stage
# is disabled.
#build:
#  stage: build
#  script:
#    - mkdir build/
#    - cd build
#    - cmake ..
#    - make -j 4

build:
  stage: build
  script:
    - git submodule init
    - git submodule update
    - mkdir build/
    - cd build
    - cmake ..
    - make -j 4
  artifacts:
      paths:
          - build/
    
test:
    stage: test
    script:
        - ctest -V
    dependencies:
        - build
        